- docs/EVENTS.md
- package-lock.json
- package.json
- src/App.tsx
- src/components/AudioBars.tsx
- src/components/Button.tsx
- src/components/Island.tsx
- src/components/Socket.tsx
- src/components/WebRTC.tsx
- src/events/CallEvents.tsx
- src/events/SocketEvents.ts
- src/index.css
- src/lib/devices/devices.ts
- src/lib/phone/call.ts
- src/lib/phone/conversation.ts
- src/lib/webrtc/types.ts
- src/models/currentCall.ts
- src/stories/App.stories.tsx
- src/styles/Island.styles.ts
- src/utils/getTranslate.ts
- src/utils/useCommittedRef.ts
- src/utils/useEventCallback.ts
- src/utils/useEventListener.ts
- src/utils/useLocalStorage.ts
- src/utils/useLongPress.ts
- tailwind.config.js
- Complete the effects on incoming call and call management
- Define call management and incoming call layout
- Add call duration and audio source bars effect
- Dispatch some messages coming from WS through custom events
- Add ping effect behind avatar on incoming call
- Make some other little changes
> Add expansion, drag effects and more

- package-lock.json
- package.json
- src/App.tsx
- src/components/Button.tsx
- src/components/CallView/Actions.tsx
- src/components/CallView/Avatar.tsx
- src/components/CallView/BackCall.tsx
- src/components/CallView/DisplayName.tsx
- src/components/CallView/index.tsx
- src/components/Hangup.tsx
- src/components/Island.tsx
- src/components/KeypadView/index.tsx
- src/components/Socket.tsx
- src/components/TransferView/ListAvatar.tsx
- src/components/TransferView/TransferActions.tsx
- src/components/TransferView/TransferList.tsx
- src/lib/phone/call.ts
- src/models/currentCall.ts
- src/models/motions.ts
- src/stories/Call.stories.tsx
- src/styles/Island.styles.ts
- tailwind.config.js
- Remove the direct transfer
- Enhance the transfer functionalities
> Enhance call transfer

- src/App.tsx
- src/components/Events.tsx
- src/components/WebRTC.tsx
- src/events/CallEvents.tsx
- src/lib/phone/call.ts
- src/lib/webrtc/messages.ts
Janus host and port must be customisable.
> Parametrize janus host and port

- src/App.tsx
- src/components/Socket.tsx
- src/components/WebRTC.tsx
- src/types/webrtc.ts
- src/utils/genericFunctions/exposeWorker.ts
- src/workers/wake_up.ts
This is useful to avoid disconnections after systems sleep.
> Manage wakeup and reload events

- src/App.tsx
- src/components/CallView/Actions.tsx
- src/components/CallView/Avatar.tsx
- src/components/WebRTC.tsx
- src/lib/webrtc/messages.ts
- src/stories/Call.stories.tsx
- Fixed missing audio during transfer call
- Created janus attach and detach event
> Fixed missing audio inside transfer

- docs/EVENTS.md
- src/App.tsx
- src/models/island.ts
Added new events:
- L `phone-island-expand`
- L `phone-island-compress`
- E `phone-island-expanded`
- E `phone-island-compressed`
> events. added expand and compress events

- package-lock.json
- public/locales/en/translation.json
- public/locales/it/translation.json
- src/components/AudioPlayerView/index.tsx
- src/components/CallView/Actions.tsx
- src/components/CallView/index.tsx
- src/components/Hangup.tsx
- src/components/IslandMotion.tsx
- src/components/RecorderView/Actions.tsx
- src/components/SwitchInputView/DropdownContent.tsx
- src/components/TransferView/TransferList.tsx
- src/events/CallEvents.tsx
- src/index.css
- src/lib/phone/call.ts
- src/models/currentCall.ts
- src/models/motions.ts
- src/services/astproxy.ts
- src/stories/Call.stories.tsx
**Listen**
**Intrude**
- - - -
**Recording**
> listen/intrude. Update phone island UI for listen and intrude mode

- src/components/Socket.tsx
**Created new event inside socket in case of busy ringing situation**
> socket. Created a phone-island-call-ringing event inside busy_ringing

- src/components/Socket.tsx
- src/events/SocketEvents.ts
- src/utils/genericFunctions/isEmpty.ts
https://github.com/NethServer/dev/issues/7031
> socket. Created new update extension event

- src/components/CallView/Timer.tsx
- src/components/CallView/index.tsx
- src/components/IslandMotion.tsx
- src/components/Socket.tsx
- src/components/WebRTC.tsx
- src/lib/webrtc/messages.ts
- tailwind.config.js
- Added safe list for tailwind css class not used in this version
- Fixed view in case of a call during an alert ( to simulate try to make a call to user who has not audio or video physical device or permission enabled )
- Removed wrong control inside ringing function in Socket.tsx
> Phone island minor fix regression after 0.8.21 version

- docs/EVENTS.md
- src/components/AlertView/index.tsx
- src/components/CallView/DisplayName.tsx
- src/components/Socket.tsx
- src/components/TextScroll.tsx
- src/events/SocketEvents.ts
- src/index.css
- src/stories/Call.stories.tsx
- tailwind.config.js
- Created new event `phone-island-call-physical` to manage `callNethLink` event from WebSocket
> Added missing phone-island event for callNethLink ws event

- src/components/Socket.tsx
- src/lib/phone/call.ts
- src/models/island.ts
- src/services/astproxy.ts
**Reference** : https://github.com/NethServer/dev/issues/7088
> fix(actions): wrong mute/unMute physical action

- docs/EVENTS.md
- src/components/Socket.tsx
- src/events/SocketEvents.ts
*See also* : 
- https://github.com/nethesis/nethcti-server/pull/324
- https://github.com/nethesis/ns8-nethvoice/pull/348
> feat(events): created new event for socket update default_device

- src/services/astproxy.ts
> fix: check if action is hangup or cancel

- public/locales/en/translation.json
- public/locales/it/translation.json
- src/App.tsx
- src/components/AlertView/index.tsx
- src/models/alerts.ts
- src/models/currentUser.ts
> fix: added call endend event on hangup

- docs/EVENTS.md
- src/App.tsx
- src/stories/Call.stories.tsx
- src/utils/genericFunctions/checkConnection.ts
> feat(socket_event): created new event for check user internet connectivity

- src/components/Socket.tsx
**Reference**: https://github.com/NethServer/dev/issues/7118
> fix(audioPlayer): wrong audio player sound on incoming call

- src/components/Socket.tsx
- src/models/player.ts
> fix(audioPlayer): broken on audio player stop

- src/components/Socket.tsx
- src/components/WebRTC.tsx
**Reference** : https://github.com/NethServer/dev/issues/7267
> fix: wrong default_device update

- src/components/Socket.tsx
- src/components/WebRTC.tsx
- src/lib/phone/call.ts
- src/models/currentCall.ts
- src/services/astproxy.ts
- src/types/user.ts
**Reference** : https://github.com/NethServer/dev/issues/7267
> fix: missing phone island on incoming call

- README.md
- bump-version.js
- package.json
- src/App.tsx
**Reference** : https://github.com/NethServer/dev/issues/7267
> fix: deleted manual store update on webrtc detach

- package.json
- src/App.tsx
- src/components/SideView/SideView.tsx
**Reference**: https://github.com/NethServer/dev/issues/7153
> feat: fix top e right dimension

- src/components/SettingsView/AudioView.tsx
- src/components/SettingsView/MicrophoneView.tsx
**Reference**: https://github.com/NethServer/dev/issues/7153
> fix: missing overflow inside settings

- src/components/AudioBars.tsx
- src/components/SideView/SideView.tsx
- src/lib/i18n.ts
- src/utils/deviceUtils.ts
**Reference**: https://github.com/NethServer/dev/issues/7153
> fix: avoid error if user has no device

- public/locales/it/translation.json
- src/components/Close.tsx
- src/components/SideView/SideView.tsx
- src/components/Socket.tsx
- src/components/WebRTC.tsx
- src/events/CallEvents.tsx
- src/events/PlayerEvents.tsx
- src/lib/player/audio.ts
- src/services/voicemail.ts
- src/stories/Call.stories.tsx
- src/types/player.ts
**Reference**:
- https://github.com/NethServer/dev/issues/7136
> fix: missing recording view

- docs/EVENTS.md
- src/App.tsx
- src/components/CallView/Actions.tsx
- src/components/IslandMotion.tsx
- src/components/SideView/SideView.tsx
- src/components/Socket.tsx
- src/components/VideoView/index.tsx
- src/components/WebRTC.tsx
- src/events/SocketEvents.ts
- src/models/currentCall.ts
- src/models/island.ts
- src/models/motions.ts
- src/models/screenShare.ts
- src/stories/Call.stories.tsx
- Fix stop screen sharing
- Fix phone island padding
- Minor fixes
Ref:
- https://github.com/NethServer/dev/issues/7148
> fix(screen sharing): fixes and improvements

- src/components/AudioPlayerView/Progress.tsx
- src/components/AudioPlayerView/index.tsx
- src/components/Close.tsx
- src/components/Island.tsx
- src/components/IslandDrag.tsx
- src/components/RecorderView/Actions.tsx
- src/models/island.ts
**Reference**:
- https://github.com/NethServer/dev/issues/7136
> fix: missing recording complete

- src/App.tsx
- src/components/AlertGuard.tsx
- src/components/AlertView/index.tsx
- src/components/Island.tsx
- src/components/Socket.tsx
- src/components/WebRTC.tsx
- src/lib/devices/devices.ts
- src/services/user.ts
- src/stories/Call.stories.tsx
**Reference** : 
- https://github.com/NethServer/dev/issues/7364
> fix: avoid to show alert on user close

- public/locales/en/translation.json
- public/locales/it/translation.json
- src/components/SideView/SideView.tsx
- src/lib/devices/devices.ts
**Reference** : 
- https://github.com/NethServer/dev/issues/7364
> fix: check camera permission on video click

- docs/EVENTS.md
- src/components/Socket.tsx
- src/components/TransferView/TransferList.tsx
**Reference**
- https://github.com/NethServer/dev/issues/7406
> fix: missing interval between hangup and new call

- src/components/SideView/SideView.tsx
- src/components/TransferButton.tsx
- src/components/VideoView/index.tsx
- src/lib/phone/call.ts
- src/lib/webrtc/messages.ts
- src/services/astproxy.ts
**Reference**: 
- https://github.com/NethServer/dev/issues/7393
- https://github.com/NethServer/dev/issues/7358
> fix: camera permission & cancel transfer

- src/components/Button.tsx
- src/components/SideView/SideView.tsx
- src/components/SideView/hooks/useSideViewLogic.ts
**Reference** :
- https://github.com/NethServer/dev/issues/7137
> fix: added missing conversations information fro url param

- src/App.tsx
- src/components/SideView/hooks/useSideViewLogic.ts
- src/components/Socket.tsx
- src/lib/phone/trunk.ts
- src/lib/user/extensions.ts
- src/models/paramUrl.ts
**References**:
- https://github.com/NethServer/dev/issues/7559
- https://github.com/NethServer/dev/issues/7512
> fix: use extensions to get throughTrunk instead of socket
